/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.IntelliJTheme;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import model.bridgePattern.GermanSubmarineMaker;
import model.bridgePattern.ItalianSubmarineMaker;
import model.bridgePattern.MexicanSubmarineMaker;
import model.decoratorPattern.Bacon;
import model.decoratorPattern.Cheese;
import model.decoratorPattern.Chicken;
import model.decoratorPattern.CrustBun;
import model.decoratorPattern.Ham;
import model.decoratorPattern.Ketchup;
import model.decoratorPattern.Levites;
import model.decoratorPattern.Onion;
import model.decoratorPattern.SoftBun;
import model.decoratorPattern.Submarine;
import model.decoratorPattern.ThickBun;
import model.decoratorPattern.Tomato;
import model.mementoPattern.Cart;
import model.mementoPattern.CartHistory;

/**
 *
 * @author NUWAA
 */
public class SubmarineShop extends javax.swing.JFrame {

    /**
     * Creates new form SubmarineShop
     */
    static SubmarineShop object;
    static Map<String, Double> bunTypes;
    static Map<String, Double> toppingTypes;

    Submarine currentSubmarine;

    Cart cart;
    CartHistory cartHistory;

    public SubmarineShop() {
        initComponents();

        cart = new Cart();
        cartHistory = new CartHistory();

        Vector<Vector> dataVector = ((DefaultTableModel) cartTable.getModel()).getDataVector();
        Vector<Vector> cartVector = new Vector<>();
        
//      Iterator Pattern
        Iterator<Vector> iterator = dataVector.iterator();
        while (iterator.hasNext()) {
            cartVector.add(iterator.next());
        }
        cart.setCart(cartVector);
        cartHistory.saveHistory(cart);

        bunTypes = new HashMap<>();
        toppingTypes = new HashMap<>();

        bunTypes.put("Crust Bun", 200.0);
        bunTypes.put("Soft Bun", 180.0);
        bunTypes.put("Thick Bun", 150.0);

        toppingTypes.put("Bacon", 150.0);
        toppingTypes.put("Cheese", 100.0);
        toppingTypes.put("Chicken", 150.0);
        toppingTypes.put("Ham", 150.0);
        toppingTypes.put("Ketchup", 20.0);
        toppingTypes.put("Levites", 20.0);
        toppingTypes.put("Onion", 20.0);
        toppingTypes.put("Tomato", 20.0);

        DefaultTableModel dtm = (DefaultTableModel) bunTypesTable.getModel();
        dtm.setRowCount(0);

        DefaultTableModel dtm2 = (DefaultTableModel) toppingsTable.getModel();
        dtm2.setRowCount(0);

        for (Map.Entry<String, Double> entry : bunTypes.entrySet()) {
            Vector vector = new Vector();
            vector.add(entry.getKey());
            vector.add(entry.getValue());
            dtm.addRow(vector);
        }

        for (Map.Entry<String, Double> entry : toppingTypes.entrySet()) {
            Vector vector = new Vector();
            vector.add(entry.getKey());
            vector.add(entry.getValue());
            dtm2.addRow(vector);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mexicanSubmarineRadioButton = new javax.swing.JRadioButton();
        italianSubmarineRadioButton = new javax.swing.JRadioButton();
        germanSubmarineRadioButton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bunTypesTable = new javax.swing.JTable();
        addToCartButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        toppingsTable = new javax.swing.JTable();
        addToBunButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        addNewButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        totalTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        paidTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        balanceTextField = new javax.swing.JTextField();
        checkoutButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Submarine Shop");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("Submarine Shop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Select Submarine Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        buttonGroup1.add(mexicanSubmarineRadioButton);
        mexicanSubmarineRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mexicanSubmarineRadioButton.setSelected(true);
        mexicanSubmarineRadioButton.setText("Mexican Submarine");

        buttonGroup1.add(italianSubmarineRadioButton);
        italianSubmarineRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        italianSubmarineRadioButton.setText("Italian Submarine");

        buttonGroup1.add(germanSubmarineRadioButton);
        germanSubmarineRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        germanSubmarineRadioButton.setText("German Submarine");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mexicanSubmarineRadioButton)
                .addGap(18, 18, 18)
                .addComponent(italianSubmarineRadioButton)
                .addGap(18, 18, 18)
                .addComponent(germanSubmarineRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mexicanSubmarineRadioButton)
                    .addComponent(italianSubmarineRadioButton)
                    .addComponent(germanSubmarineRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Select Bun Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        bunTypesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bun Type", "Price"
            }
        ));
        jScrollPane1.setViewportView(bunTypesTable);
        if (bunTypesTable.getColumnModel().getColumnCount() > 0) {
            bunTypesTable.getColumnModel().getColumn(1).setMinWidth(150);
            bunTypesTable.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        addToCartButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addToCartButton.setText("Add To Cart");
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(addToCartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Select Toppings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        toppingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Topping", "Price"
            }
        ));
        jScrollPane2.setViewportView(toppingsTable);
        if (toppingsTable.getColumnModel().getColumnCount() > 0) {
            toppingsTable.getColumnModel().getColumn(1).setMinWidth(150);
            toppingsTable.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        addToBunButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addToBunButton.setText("Add To Bun");
        addToBunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToBunButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(addToBunButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToBunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cart", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Submarine", "Price"
            }
        ));
        jScrollPane3.setViewportView(cartTable);
        if (cartTable.getColumnModel().getColumnCount() > 0) {
            cartTable.getColumnModel().getColumn(1).setMinWidth(150);
            cartTable.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        addNewButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addNewButton.setText("Add New");
        addNewButton.setEnabled(false);
        addNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewButtonActionPerformed(evt);
            }
        });

        undoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        undoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-undo-30.png"))); // NOI18N
        undoButton.setEnabled(false);
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        redoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        redoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons8-redo-30.png"))); // NOI18N
        redoButton.setEnabled(false);
        redoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoButtonActionPerformed(evt);
            }
        });

        totalTextField.setEditable(false);
        totalTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalTextField.setText("0.0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Paid : ");

        paidTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paidTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paidTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paidTextFieldKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Balance : ");

        balanceTextField.setEditable(false);
        balanceTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        balanceTextField.setText("0.0");

        checkoutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkoutButton.setText("Checkout");
        checkoutButton.setEnabled(false);
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/submarine-250x120.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addNewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(undoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paidTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(balanceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(checkoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(addNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(undoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paidTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(balanceTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = bunTypesTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a Bun Type", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String keyWord = bunTypesTable.getValueAt(selectedRow, 0).toString();

        switch (keyWord) {
            case "Crust Bun":
                this.currentSubmarine = new CrustBun("-"+keyWord, bunTypes.get(keyWord));
                break;
            case "Soft Bun":
                this.currentSubmarine = new SoftBun("-"+keyWord, bunTypes.get(keyWord));
                break;
            case "Thick Bun":
                this.currentSubmarine = new ThickBun("-"+keyWord, bunTypes.get(keyWord));
                break;
        }

        if (mexicanSubmarineRadioButton.isSelected()) {
            MexicanSubmarineMaker mexicanSubmarineMaker = new MexicanSubmarineMaker(currentSubmarine);
            currentSubmarine = mexicanSubmarineMaker.prepare();
        } else if (italianSubmarineRadioButton.isSelected()) {
            ItalianSubmarineMaker italianSubmarineMaker = new ItalianSubmarineMaker(currentSubmarine);
            currentSubmarine = italianSubmarineMaker.prepare();
        } else if (germanSubmarineRadioButton.isSelected()) {
            GermanSubmarineMaker germanSubmarineMaker = new GermanSubmarineMaker(currentSubmarine);
            currentSubmarine = germanSubmarineMaker.prepare();
        }

        if (cartTable.getRowCount() == 0) {
            DefaultTableModel dtm = (DefaultTableModel) cartTable.getModel();
            dtm.addRow(new Vector());
            addNewButton.setEnabled(true);
            undoButton.setEnabled(true);
            redoButton.setEnabled(true);
        }
        int rowCount = cartTable.getRowCount();
        cartTable.setValueAt(currentSubmarine.getDescription(), rowCount - 1, 0);
        cartTable.setValueAt(currentSubmarine.getCost(), rowCount - 1, 1);
        calculateTotal();

        Vector<Vector> dataVector = ((DefaultTableModel) cartTable.getModel()).getDataVector();
        Vector<Vector> cartVector = new Vector<>();
        Iterator<Vector> iterator = dataVector.iterator();
        while (iterator.hasNext()) {
            cartVector.add(iterator.next());
        }
        cart.setCart(cartVector);
        cartHistory.saveHistory(cart);
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void addToBunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToBunButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = toppingsTable.getSelectedRow();

        if (currentSubmarine == null) {
            JOptionPane.showMessageDialog(this, "Add to cart a Submarine First", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Select a Topping", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String keyWord = toppingsTable.getValueAt(selectedRow, 0).toString();
        switch (keyWord) {
            case "Bacon":
                this.currentSubmarine = new Bacon(currentSubmarine, toppingTypes.get(keyWord));
                break;
            case "Cheese":
                this.currentSubmarine = new Cheese(currentSubmarine, toppingTypes.get(keyWord));
                break;
            case "Chicken":
                this.currentSubmarine = new Chicken(currentSubmarine, toppingTypes.get(keyWord));
                break;
            case "Ham":
                this.currentSubmarine = new Ham(currentSubmarine, toppingTypes.get(keyWord));
                break;
            case "Ketchup":
                this.currentSubmarine = new Ketchup(currentSubmarine, toppingTypes.get(keyWord));
                break;
            case "Levites":
                this.currentSubmarine = new Levites(currentSubmarine, toppingTypes.get(keyWord));
                break;
            case "Onion":
                this.currentSubmarine = new Onion(currentSubmarine, toppingTypes.get(keyWord));
                break;
            case "Tomato":
                this.currentSubmarine = new Tomato(currentSubmarine, toppingTypes.get(keyWord));
                break;

        }

        int rowCount = cartTable.getRowCount();
        cartTable.setValueAt(currentSubmarine.getDescription(), rowCount - 1, 0);
        cartTable.setValueAt(currentSubmarine.getCost(), rowCount - 1, 1);
        calculateTotal();

        Vector<Vector> dataVector = ((DefaultTableModel) cartTable.getModel()).getDataVector();
        Vector<Vector> cartVector = new Vector<>();
        Iterator<Vector> iterator = dataVector.iterator();
        while (iterator.hasNext()) {
            cartVector.add(iterator.next());
        }
        cart.setCart(cartVector);
        cartHistory.saveHistory(cart);
    }//GEN-LAST:event_addToBunButtonActionPerformed

    private void addNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewButtonActionPerformed
        // TODO add your handling code here:
        currentSubmarine = null;
        DefaultTableModel dtm = (DefaultTableModel) cartTable.getModel();
        dtm.addRow(new Vector());

        Vector<Vector> dataVector = ((DefaultTableModel) cartTable.getModel()).getDataVector();
        Vector<Vector> cartVector = new Vector<>();
        Iterator<Vector> iterator = dataVector.iterator();
        while (iterator.hasNext()) {
            cartVector.add(iterator.next());
        }
        cart.setCart(cartVector);
        cartHistory.saveHistory(cart);
    }//GEN-LAST:event_addNewButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        // TODO add your handling code here:cartHistory.undo(cart);
        cartHistory.undo(cart);
        Vector model = cart.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel) cartTable.getModel();
        dtm2.setRowCount(0);

//      Iterator Pattern
        Iterator iterator = model.iterator();
        while (iterator.hasNext()) {
            Vector next = (Vector) iterator.next();
            dtm2.addRow(next);
        }

        calculateTotal();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void redoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoButtonActionPerformed
        // TODO add your handling code here:
        cartHistory.redo(cart);
        Vector model = cart.getModel();
        DefaultTableModel dtm2 = (DefaultTableModel) cartTable.getModel();
        dtm2.setRowCount(0);

        Iterator iterator = model.iterator();
        while (iterator.hasNext()) {
            Vector next = (Vector) iterator.next();
            dtm2.addRow(next);
        }

        calculateTotal();
    }//GEN-LAST:event_redoButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Check Out Completed", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void paidTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidTextFieldKeyReleased
        // TODO add your handling code here:
        double total = Double.parseDouble(totalTextField.getText());
        double paid = Double.parseDouble(paidTextField.getText());

        balanceTextField.setText(String.valueOf(paid - total));

        if (paid >= total) {
            checkoutButton.setEnabled(true);
        }


    }//GEN-LAST:event_paidTextFieldKeyReleased

    private void paidTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidTextFieldKeyTyped
        // TODO add your handling code here:
        if (((Character.isDigit(evt.getKeyChar())) | (String.valueOf(evt.getKeyChar()).equals(".")))) {
            if (paidTextField.getText().contains(".")) {
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_paidTextFieldKeyTyped

//  Singleton pattern
    public static SubmarineShop getObject() {
        if (object == null) {
            object = new SubmarineShop();
        }
        return object;
    }

    private void calculateTotal() {
        double total = 0.0;
        for (int i = 0; i < cartTable.getRowCount(); i++) {
            total = total + Double.parseDouble(cartTable.getValueAt(i, 1).toString());
        }
        totalTextField.setText(String.valueOf(total));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SubmarineShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SubmarineShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SubmarineShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SubmarineShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }

        try {
//            UIManager.setLookAndFeel(new FlatLightLaf());
            IntelliJTheme.setup(SubmarineShop.class.getResourceAsStream(
                    "/resources/themes/arc-theme.theme.json"));
            UIManager.put("Table.showHorizontalLines", true);
            UIManager.put("Table.showVerticalLines", true);
            UIManager.put("ScrollBar.showButtons", true);
            UIManager.put("ScrollBar.width", 16);
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubmarineShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewButton;
    private javax.swing.JButton addToBunButton;
    private javax.swing.JButton addToCartButton;
    private javax.swing.JTextField balanceTextField;
    private javax.swing.JTable bunTypesTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JRadioButton germanSubmarineRadioButton;
    private javax.swing.JRadioButton italianSubmarineRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton mexicanSubmarineRadioButton;
    private javax.swing.JTextField paidTextField;
    private javax.swing.JButton redoButton;
    private javax.swing.JTable toppingsTable;
    private javax.swing.JTextField totalTextField;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables
}
